Repository HoloENFans/hef-website-cms, pull requests merged in 2024-05, with the labels that each got.

#219 feat: add sections and hide unrelated collections from users
  pnpm-lock.yaml
  src/collections/Events.ts
  src/collections/FormSubmissions.ts
  src/collections/Guilds.ts
  src/collections/Project.ts
  src/collections/Submissions.ts
  src/collections/Users.ts
  src/lib/checkSection.ts
  src/migrations/sections.ts
  src/payload-types.ts
Labels: Type: Enhancement, Priority: High

#222 Automatically deploy to k8s and apply migrations
  .github/workflows/build_and_deploy.yml
  kubernetes/deployment.yml
  kubernetes/ingress.yml
  src/collections/Media.ts
Labels: Type: Enhancement, Priority: Medium

#227 Add People and Links collections
  src/collections/Links.ts
  src/collections/People.ts
  src/payload.config.ts
Labels: Type: Feature, Priority: Medium
